# Generated by Django 3.1.7 on 2021-04-05 21:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweets', '0005_tweet_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='retweeted_by',
            field=models.ManyToManyField(related_name='tweeted_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
