# Generated by Django 3.1.7 on 2021-05-04 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0008_auto_20210504_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='parent',
            field=models.ForeignKey(default=41, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tweets.tweet'),
            preserve_default=False,
        ),
    ]
